### ISSUE TITLE
Deploy to Bluemix button does not work

### ISSUE THREAD

**Issue by ChrisParsonsDev** [watson-developer-cloud/node-red-bluemix-starter#27]
The deploy to Bluemix button fails to deploy. Bluemix no longer creates the Cloudant DB as part of the build process.

Workaround: 

Add a CloudantNOSQL service instance to the Bluemix space called `sample-node-red-cloudantNoSQLDB`  and launch the service. 

Then click the "deploy to Bluemix" button on this page.

**Comment by ylecleach** [comment]
Hi Chris,

The Cloudant Shared plan on Bluemix has recently be removed.
We should use the "Lite" plan.
Do you want me to update the following file ?
https://github.com/watson-developer-cloud/node-red-bluemix-starter/blob/master/manifest.yml

**Comment by ylecleach** [comment]
The Shared plan has been probably removed today

**Comment by ChrisParsonsDev** [comment]
@ylecleach Yes please, go ahead and make the change.

**Comment by ylecleach** [comment]
in progress. 
notice that it was done by Nick 10 days ago on Bluemix NR Starter : https://github.com/ibmets/node-red-bluemix-starter/blob/master/manifest.yml
