### ISSUE TITLE
How to run this locally?

### ISSUE THREAD

**Issue by playground** [watson-developer-cloud/node-red-bluemix-starter#28]
npm start gives errors.

What values should  process.env.VCAP_APPLICATION and VCAP_SERVICES have?

**Comment by chughts** [comment]
This is a Bluemix starter, designed as a boilerplate to run on Bluemix. If you do want Node-RED to run locally then you should run

````
npm install -g node-red
````

Then start Node-RED locally - 

````
npm start
````

If you want to add additional nodes like the watson nodes

````
npm install node-red-node-watson
````

Essentially following the set-up guidelines in the contributing document for node-red-node-watson -
https://github.com/watson-developer-cloud/node-red-node-watson/blob/master/CONTRIBUTING.md

**Comment by playground** [comment]
Thanks @chughts.  One other question, do you have an example of showing when submitting a PR to a github repo with CI/CD linking to Bluemix?

**Comment by chughts** [comment]
Afraid not. You will need to redirect the question to JazzHub.
