### ISSUE TITLE
Remove use of process.env.VCAP_APP_PORT

### ISSUE THREAD

**Issue by knolleary** [watson-developer-cloud/node-red-bluemix-starter#30]
Hi,

in the very near future process.env.VCAP_APP_PORT will no longer be available in Bluemix - this environment variable has been replaced by process.env.PORT instead.

Ref: https://github.com/ibmets/node-red-bluemix-starter/issues/6

Please update this starter as soon as possible.

Thanks,
Nick

**Comment by chughts** [comment]
@knolleary Thanks for the heads-up, will make the change

**Comment by chughts** [comment]
Fixed in #31
