### ISSUE TITLE
Where/how to specify language in speech to text node? 

### ISSUE THREAD

**Issue by playground** [watson-developer-cloud/node-red-bluemix-starter#35]
I'm getting getting "Missing audio language configuration, unable to process speech.

Here is 
![image](https://cloud.githubusercontent.com/assets/243495/21729931/48c62df0-d41b-11e6-9750-5574c06dad85.png)

**Comment by chughts** [comment]
This is not the correct forum for simple usage questions like this. This forum is reserved for bugs and feature requests. 

Please post your question on developerworks answers where it will be answered. https://developer.ibm.com/answers/topics/watson/
